apiVersion: v1
kind: Service
metadata:
  name: kuard-service
spec:
  selector:
    app: frontend
    soft: nginx
  ports:
  - port: 80           # Port du Service (accessible depuis l'intérieur du cluster)
    targetPort: 8080   # Port du conteneur (où écoute kuard)
    protocol: TCP
