apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calculatrice-ingress
  namespace: namouchi-bazzi-andriamasinoro
  annotations:
    # IMPORTANT: Comme spécifié dans l'énoncé
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  # URL de développement
  - host: calculatrice-dev-namouchi_mohamed_amine-bazzi_taher-faniry_andriamasinoro.polytech-dijon.kiowy.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service  # À créer plus tard
            port:
              number: 5000
  
  # URL de production  
  - host: calculatrice-namouchi_mohamed_amine-bazzi_taher-faniry_andriamasinoro.polytech-dijon.kiowy.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service  # À créer plus tard
            port:
              number: 5000
